// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: proto/tmp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TmpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TmpRequest) Reset() {
	*x = TmpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TmpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TmpRequest) ProtoMessage() {}

func (x *TmpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TmpRequest.ProtoReflect.Descriptor instead.
func (*TmpRequest) Descriptor() ([]byte, []int) {
	return file_proto_tmp_proto_rawDescGZIP(), []int{0}
}

func (x *TmpRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TmpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TmpResponse) Reset() {
	*x = TmpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TmpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TmpResponse) ProtoMessage() {}

func (x *TmpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TmpResponse.ProtoReflect.Descriptor instead.
func (*TmpResponse) Descriptor() ([]byte, []int) {
	return file_proto_tmp_proto_rawDescGZIP(), []int{1}
}

func (x *TmpResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_tmp_proto protoreflect.FileDescriptor

var file_proto_tmp_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x74, 0x6d, 0x70, 0x22, 0x1e, 0x0a, 0x0a, 0x74, 0x6d, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1f, 0x0a, 0x0b, 0x74, 0x6d, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xf5, 0x01, 0x0a, 0x0a, 0x54, 0x6d, 0x70, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x50, 0x43, 0x12, 0x0f, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x74, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x74, 0x6d, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x50, 0x43, 0x12, 0x0f, 0x2e, 0x74, 0x6d,
	0x70, 0x2e, 0x74, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x74,
	0x6d, 0x70, 0x2e, 0x74, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x12, 0x39, 0x0a, 0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x52, 0x50, 0x43, 0x12, 0x0f, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x74, 0x6d, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x74, 0x6d,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x42, 0x0a, 0x19, 0x62,
	0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x50, 0x43, 0x12, 0x0f, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x74,
	0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x74, 0x6d, 0x70, 0x2e,
	0x74, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tmp_proto_rawDescOnce sync.Once
	file_proto_tmp_proto_rawDescData = file_proto_tmp_proto_rawDesc
)

func file_proto_tmp_proto_rawDescGZIP() []byte {
	file_proto_tmp_proto_rawDescOnce.Do(func() {
		file_proto_tmp_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tmp_proto_rawDescData)
	})
	return file_proto_tmp_proto_rawDescData
}

var file_proto_tmp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_tmp_proto_goTypes = []interface{}{
	(*TmpRequest)(nil),  // 0: tmp.tmpRequest
	(*TmpResponse)(nil), // 1: tmp.tmpResponse
}
var file_proto_tmp_proto_depIdxs = []int32{
	0, // 0: tmp.TmpService.unaryRPC:input_type -> tmp.tmpRequest
	0, // 1: tmp.TmpService.serverStreamingRPC:input_type -> tmp.tmpRequest
	0, // 2: tmp.TmpService.clientStreamingRPC:input_type -> tmp.tmpRequest
	0, // 3: tmp.TmpService.bidirectionalStreamingRPC:input_type -> tmp.tmpRequest
	1, // 4: tmp.TmpService.unaryRPC:output_type -> tmp.tmpResponse
	1, // 5: tmp.TmpService.serverStreamingRPC:output_type -> tmp.tmpResponse
	1, // 6: tmp.TmpService.clientStreamingRPC:output_type -> tmp.tmpResponse
	1, // 7: tmp.TmpService.bidirectionalStreamingRPC:output_type -> tmp.tmpResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tmp_proto_init() }
func file_proto_tmp_proto_init() {
	if File_proto_tmp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tmp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TmpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TmpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tmp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tmp_proto_goTypes,
		DependencyIndexes: file_proto_tmp_proto_depIdxs,
		MessageInfos:      file_proto_tmp_proto_msgTypes,
	}.Build()
	File_proto_tmp_proto = out.File
	file_proto_tmp_proto_rawDesc = nil
	file_proto_tmp_proto_goTypes = nil
	file_proto_tmp_proto_depIdxs = nil
}
